server:
  tomcat:
    uri-encoding: UTF-8
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:~/Sources/tmp/testdb;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 10

# 구글 Custom Search API 키, 구글 검색 엔진 키
app:
  url: https://www.googleapis.com/customsearch/v1
  key: your api key
  cx: your search engine key